name: Bug Report
description: Report an unexpected behavior or issue
title: "[BUG] Describe the problem"
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      placeholder: "Explain what is going wrong"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: "1. Go to...\n2. Click on...\n3. See the error..."
  - type: input
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: "What did you expect to happen?"
