name: Chore Task
description: Request a non-functional change (e.g., refactor, config, tooling)
title: "[CHORE] Task title"
labels: [chore]
body:
  - type: textarea
    id: task
    attributes:
      label: Describe the Task
      placeholder: "What needs to be done?"
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Why is this necessary?
      placeholder: "Explain the reasoning or context"
